const ACADEMIES = [
  {
    id: "pzta",
    name: "Player Zone Tennis Academy (PZTA)",
    country: "Serbia",
    countryFlag: "🇷🇸",
    city: "Belgrade",
    website: "https://playerzonetennis.rs",
    contact: "+381 60 43 19 966",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: true,
    airport: { name: "Belgrade Nikola Tesla Airport", code: "BEG", distance: "18 km", driveTime: "20 min" },
    beach: { distance: null, description: "Inland — nearest Adriatic coast ~400 km to Montenegro" },
    climate: "belgrade",
    priceRange: { from: 1100, to: 4500, unit: "month", display: "€1,100–€4,500/mo" },
    programs: [
      { name: "Basic", price: "€1,500/mo", desc: "12h tennis/week, conditioning, coach support" },
      { name: "Camp (Beginner/Intermediate)", price: "€1,100/mo", desc: "Training camp format" },
      { name: "Camp (Advanced)", price: "€1,430/mo", desc: "Advanced camp format" },
      { name: "Professional", price: "€2,350/mo", desc: "Intensive training, conditioning, recovery, tournament planning" },
      { name: "Pro+", price: "€3,500/mo", desc: "More conditioning, private lessons, personalized mentoring" },
      { name: "VIP", price: "€4,500/mo", desc: "Unlimited tennis, conditioning, massages, mental training" }
    ],
    coaches: [
      { name: "David Savić", credential: "GPTCA B (ATP Certified)", background: "Coached top-100 ATP & WTA players", atpWta: false, bestRanking: null, rankingNote: "Top-100 ATP/WTA coach" },
      { name: "Ivan Đurđević", credential: "GPTCA B (ATP Certified)", background: "Experience with top WTA players & Serbian national team", atpWta: false, bestRanking: null },
      { name: "Milana Spremo", credential: "GPTCA B", background: "Former WTA player; coach of Serbian national team U18", atpWta: true, bestRanking: null, rankingNote: "Former WTA player" },
      { name: "Marko Savić", credential: "ITF Level 2", background: "National coach of Serbia 10+ years", atpWta: false, bestRanking: null },
      { name: "Milenko Pisarić", credential: "C TSS, C GPTCA", background: "20+ years international experience (Serbia, USA)", atpWta: false, bestRanking: null }
    ],
    bestCoachRanking: null,
    facilities: "Multiple locations in Belgrade",
    notableAlumni: [],
    description: "Full-service academy with transparent pricing, conditioning, mental coaching, injury prevention, tournament travel, accommodation & logistics."
  },
  {
    id: "tipsarevic",
    name: "Tipsarević Tennis Academy",
    country: "Serbia",
    countryFlag: "🇷🇸",
    city: "Belgrade",
    website: "https://www.tipsarevictennisacademy.com",
    individualLessons: true,
    boarding: true,
    level: "Elite",
    starred: false,
    airport: { name: "Belgrade Nikola Tesla Airport", code: "BEG", distance: "18 km", driveTime: "20 min" },
    beach: { distance: null, description: "Inland — nearest Adriatic coast ~400 km to Montenegro" },
    climate: "belgrade",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Elite Training", price: "Contact", desc: "Personalized coaching, global tournament exposure" },
      { name: "Tennis + Education", price: "Contact", desc: "Flexible schooling for juniors (ages 13+)" },
      { name: "Weekly Camps", price: "Contact", desc: "Intensive camp format" }
    ],
    coaches: [
      { name: "Janko Tipsarević", credential: "Former ATP Player", background: "ATP World No. 8 (2012), ATP Finals participant, Grand Slam QF", atpWta: true, bestRanking: 8, rankingNote: "ATP #8" }
    ],
    bestCoachRanking: 8,
    facilities: "Clay courts, hard court (US Open surface), fitness center, recovery facilities, on-site boarding accommodation",
    notableAlumni: ["Laslo Djere", "Yuichi Sugita", "Dušan Lajović"],
    description: "Only full-boarding tennis academy in Serbia. Founded by former ATP World No. 8 Janko Tipsarević."
  },
  {
    id: "vranes",
    name: "Dejan Vraneš Tennis Academy",
    country: "Serbia",
    countryFlag: "🇷🇸",
    city: "Belgrade",
    website: "https://vranesacademy.com",
    individualLessons: true,
    boarding: false,
    level: "Elite",
    starred: false,
    airport: { name: "Belgrade Nikola Tesla Airport", code: "BEG", distance: "18 km", driveTime: "20 min" },
    beach: { distance: null, description: "Inland — nearest Adriatic coast ~400 km to Montenegro" },
    climate: "belgrade",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Elite Development", price: "Contact", desc: "High-performance, video analysis, sports technology" },
      { name: "Junior Programs", price: "Contact", desc: "Holistic approach: nutrition, mental conditioning, recovery" }
    ],
    coaches: [
      { name: "Dejan Vraneš", credential: "Former Fed Cup Captain", background: "Coached Novak Djokovic (early dev), Ana Ivanovic (WTA #1), Olga Danilovic; Serbian Men's Olympic Team coach 2008 & 2012", atpWta: false, bestRanking: null, rankingNote: "Coached ATP #1 & WTA #1" }
    ],
    bestCoachRanking: null,
    coachedTopPlayer: 1,
    facilities: "Belgrade-based courts",
    notableAlumni: ["Novak Djokovic (early)", "Ana Ivanovic", "Olga Danilovic"],
    description: "Headed by former Serbian Fed Cup captain who coached Novak Djokovic and Ana Ivanovic."
  },
  {
    id: "premium-tennis",
    name: "Premium Tennis Academy",
    country: "Serbia",
    countryFlag: "🇷🇸",
    city: "Belgrade",
    website: "https://premiumtennis.net",
    individualLessons: true,
    boarding: false,
    level: "Pro",
    starred: false,
    airport: { name: "Belgrade Nikola Tesla Airport", code: "BEG", distance: "18 km", driveTime: "20 min" },
    beach: { distance: null, description: "Inland — nearest Adriatic coast ~400 km to Montenegro" },
    climate: "belgrade",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Personalized Training", price: "Contact", desc: "Sparring, fitness, career planning, mental training" }
    ],
    coaches: [
      { name: "Ognjen Jovanovic", credential: "ATP Top-50 Coach", background: "Co-head coach for Miomir Kecmanovic (ATP ~30)", atpWta: false, bestRanking: null, rankingNote: "ATP top-50 coach" }
    ],
    bestCoachRanking: null,
    coachedTopPlayer: 30,
    facilities: "Professional courts, accommodation for international players",
    notableAlumni: ["Miomir Kecmanovic"],
    description: "Headed by ATP top-50 coach, co-head coach for Miomir Kecmanovic."
  },
  {
    id: "academy-ada",
    name: "Tennis Academy ADA (Bogdan Obradovic)",
    country: "Serbia",
    countryFlag: "🇷🇸",
    city: "Belgrade",
    website: "https://www.bogdanobradovic-tennisacademy.com",
    individualLessons: true,
    boarding: false,
    level: "Junior/All",
    starred: false,
    airport: { name: "Belgrade Nikola Tesla Airport", code: "BEG", distance: "18 km", driveTime: "20 min" },
    beach: { distance: null, description: "Inland — nearest Adriatic coast ~400 km to Montenegro" },
    climate: "belgrade",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Junior Tennis School", price: "Contact", desc: "Ages 6+, clay courts" }
    ],
    coaches: [
      { name: "Bogdan Obradovic", credential: "Former Djokovic Coach", background: "Former coach of Novak Djokovic (early years)", atpWta: false, bestRanking: null, rankingNote: "Coached ATP #1" }
    ],
    bestCoachRanking: null,
    coachedTopPlayer: 1,
    facilities: "7 courts (5 clay + additional surfaces), Ada Ciganlija",
    notableAlumni: ["Novak Djokovic (early)"],
    description: "Founded by Bogdan Obradovic, former coach of Novak Djokovic's early years."
  },
  {
    id: "supreme-tennis",
    name: "Supreme Tennis Academy",
    country: "Serbia",
    countryFlag: "🇷🇸",
    city: "Belgrade",
    website: "https://tennisacademysupreme.com/en/",
    individualLessons: true,
    boarding: false,
    level: "Pro",
    starred: false,
    airport: { name: "Belgrade Nikola Tesla Airport", code: "BEG", distance: "18 km", driveTime: "20 min" },
    beach: { distance: null, description: "Inland — nearest Adriatic coast ~400 km to Montenegro" },
    climate: "belgrade",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Individual Training", price: "Contact", desc: "Personalized program" },
      { name: "Tournament Accompaniment", price: "Contact", desc: "TE, ITF events" }
    ],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Tennis base with on-site apartments",
    notableAlumni: ["Aleksandra Krunić"],
    description: "Individual training, tournament accompaniment, on-site apartment accommodation."
  },
  {
    id: "serbia-tennis-academy",
    name: "Serbia Tennis Academy (STA)",
    country: "Serbia",
    countryFlag: "🇷🇸",
    city: "Belgrade",
    website: "https://serbiatennisacademy.com",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Belgrade Nikola Tesla Airport", code: "BEG", distance: "18 km", driveTime: "20 min" },
    beach: { distance: null, description: "Inland — nearest Adriatic coast ~400 km to Montenegro" },
    climate: "belgrade",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Intensive Program", price: "Contact", desc: "Full intensive training" },
      { name: "Semi-Intensive", price: "Contact", desc: "Flexible schedule" },
      { name: "Tennis Camps", price: "Contact", desc: "Seasonal camps" }
    ],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Up to 15 clay courts + 1 indoor hard court",
    notableAlumni: [],
    description: "Intensive & semi-intensive programs. International coaching experience (China, Switzerland, Germany, USA)."
  },
  {
    id: "ljubicic",
    name: "Ljubičić Tennis Academy",
    country: "Croatia",
    countryFlag: "🇭🇷",
    city: "Mali Lošinj",
    website: "https://ljubicic.academy",
    individualLessons: true,
    boarding: true,
    level: "Elite",
    starred: true,
    airport: { name: "Rijeka Airport", code: "RJK", distance: "85 km", driveTime: "2.5 hrs (drive+ferry)" },
    beach: { distance: 0, description: "🏖️ 0 km — island location, beaches within walking distance" },
    climate: "mali-losinj",
    priceRange: { from: null, to: null, unit: "week", display: "Contact (premium)" },
    programs: [
      { name: "Academy Pro", price: "Contact", desc: "Intensive competitive training" },
      { name: "Weekly Tennis Camps", price: "Contact", desc: "Juniors & adults, all levels" },
      { name: "Vacation + Tennis", price: "Contact", desc: "Mediterranean island packages" }
    ],
    coaches: [
      { name: "Ivan Ljubičić", credential: "Former ATP Player / Federer's Coach", background: "ATP World No. 3, Indian Wells champion, Olympic bronze, coached Roger Federer 2016–2022", atpWta: true, bestRanking: 3, rankingNote: "ATP #3" },
      { name: "Luka Cvjetković", credential: "Head Coach", background: "Full-time academy head coach", atpWta: false, bestRanking: null }
    ],
    bestCoachRanking: 3,
    facilities: "13 courts, gym, physio, luxury accommodation (hotels, villas). 260+ sunny days/year",
    notableAlumni: [],
    description: "Founded by Ivan Ljubičić (ATP #3, Roger Federer's coach). Mediterranean island setting with luxury facilities."
  },
  {
    id: "ilirija",
    name: "Ilirija Tennis Academy",
    country: "Croatia",
    countryFlag: "🇭🇷",
    city: "Biograd na Moru",
    website: "https://www.ilirijatennisacademy.net",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Zadar Airport", code: "ZAD", distance: "30 km", driveTime: "30 min" },
    beach: { distance: 0.1, description: "🏖️ ~0.1 km — coastal town, beaches within walking distance" },
    climate: "biograd",
    priceRange: { from: 630, to: 1080, unit: "week", display: "€630–€1,080/wk" },
    programs: [
      { name: "Pro Tennis Program", price: "€800/wk", desc: "Daily private lesson + 2h group + 1h fitness/video" },
      { name: "Ladies Tennis Week", price: "€690/wk", desc: "Women-focused program" },
      { name: "Tennis & Yoga", price: "€770/wk", desc: "Combined program" },
      { name: "Tennis + Sail", price: "€1,080/wk", desc: "Swing the Racket & Sail" },
      { name: "Tennis + Nature", price: "€750/wk", desc: "National Park excursions included" }
    ],
    coaches: [
      { name: "Milan Zorić", credential: "ATP Coach", background: "Private coach of Iva Majoli (WTA #2, RG champion); coached Ana Vrljić, Darija Jurak", atpWta: false, bestRanking: null, rankingNote: "Coached WTA #2" },
      { name: "Robert Suevich", credential: "Former ATP Player", background: "ATP ~850, played Wimbledon & RG; coached Andrei Pavel (ATP #13)", atpWta: true, bestRanking: 850, rankingNote: "ATP ~850; coached ATP #13" },
      { name: "Mario Jukić", credential: "Former Junior International", background: "Hitting coach for Borna Ćorić and Donna Vekić", atpWta: false, bestRanking: null, rankingNote: "Coached ATP/WTA players" }
    ],
    bestCoachRanking: 850,
    coachedTopPlayer: 2,
    facilities: "20+ coaches, courts in Biograd na Moru (Dalmatian coast)",
    notableAlumni: ["Ajla Tomljanović", "Borna Ćorić (connection)", "Donna Vekić (connection)"],
    description: "Combines tennis with Croatian tourism: sailing, national parks, yoga, cycling. 20+ coaches."
  },
  {
    id: "tk-firule",
    name: "TK Firule",
    country: "Croatia",
    countryFlag: "🇭🇷",
    city: "Split",
    website: null,
    individualLessons: true,
    boarding: false,
    level: "Historic club",
    starred: false,
    airport: { name: "Split Airport", code: "SPU", distance: "25 km", driveTime: "30 min" },
    beach: { distance: 0.2, description: "🏖️ ~0.2 km — coastal city, Bačvice beach within walking distance" },
    climate: "split",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Historic tennis club in Split",
    notableAlumni: ["Goran Ivanišević (ATP #2, Wimbledon champion)"],
    description: "The club where Goran Ivanišević developed. One of Croatia's most important tennis clubs."
  },
  {
    id: "tenis-akademija-split",
    name: "Tenis Akademija Split",
    country: "Croatia",
    countryFlag: "🇭🇷",
    city: "Split",
    website: "https://tenis-akademija-split.com",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Split Airport", code: "SPU", distance: "25 km", driveTime: "30 min" },
    beach: { distance: 0.2, description: "🏖️ ~0.2 km — coastal city, Bačvice beach within walking distance" },
    climate: "split",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Training for all ages and skill levels",
    notableAlumni: [],
    description: "Training for all ages and skill levels in Split."
  },
  {
    id: "tk-agrofert",
    name: "TK Agrofert Prostějov",
    country: "Czech Republic",
    countryFlag: "🇨🇿",
    city: "Prostějov",
    website: "https://www.tkagrofert.cz",
    individualLessons: true,
    boarding: false,
    level: "Elite",
    starred: true,
    airport: { name: "Brno-Tuřany Airport", code: "BRQ", distance: "63 km", driveTime: "50 min" },
    beach: { distance: null, description: "Landlocked — Baltic ~530 km; Adriatic ~750 km" },
    climate: "prostejov",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Junior Development", price: "Contact", desc: "U14, U18 pathway" },
      { name: "High Performance", price: "Contact", desc: "Youth-to-elite pathway" }
    ],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Major complex, indoor/outdoor courts, rehabilitation zone, new tennis hall",
    notableAlumni: ["Petra Kvitová (WTA #2)", "Tomáš Berdych (ATP #4)", "Barbora Krejčíková (WTA #2)", "Karolína Plíšková (WTA #1)", "Radek Štěpánek (ATP #8)", "Jiří Novák (ATP #5)", "Jiří Lehečka (ATP #14)", "Jakub Menšík", "Tomáš Macháč"],
    description: "Arguably #1 tennis academy in Czech Republic. Produced more Grand Slam champions than any other East European academy. Founded 1900."
  },
  {
    id: "sparta-prague",
    name: "TK Sparta Prague",
    country: "Czech Republic",
    countryFlag: "🇨🇿",
    city: "Prague",
    website: "http://www.tkspartapraha.cz",
    individualLessons: true,
    boarding: false,
    level: "Elite",
    starred: false,
    airport: { name: "Václav Havel Airport Prague", code: "PRG", distance: "17 km", driveTime: "25 min" },
    beach: { distance: null, description: "Landlocked — Baltic ~430 km; Adriatic ~700 km" },
    climate: "prague",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Academy (ages 9+)", price: "Contact", desc: "All performance levels" }
    ],
    coaches: [],
    bestCoachRanking: null,
    facilities: "23 outdoor + 12 indoor courts. Hosts WTA Prague Open & ATP Challenger.",
    notableAlumni: ["Jan Kodeš (ATP #5, 3× GS)", "Hana Mandlíková (WTA #3, 4× GS)", "Petra Kvitová (WTA #2)", "Karolína Plíšková (WTA #1)", "Tomáš Macháč"],
    description: "One of Czech Republic's most prestigious clubs. Founded 1905. 35 courts total."
  },
  {
    id: "pliskova-academy",
    name: "Plíšková Tennis Academy",
    country: "Czech Republic",
    countryFlag: "🇨🇿",
    city: "Prague",
    website: "http://pliskovatennis.academy/en",
    individualLessons: true,
    boarding: false,
    level: "Pro/Junior",
    starred: false,
    airport: { name: "Václav Havel Airport Prague", code: "PRG", distance: "17 km", driveTime: "25 min" },
    beach: { distance: null, description: "Landlocked — Baltic ~430 km; Adriatic ~700 km" },
    climate: "prague",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Junior Development", price: "Contact", desc: "Youth programs" },
      { name: "ATP/WTA Professional", price: "Contact", desc: "Pro-level training" },
      { name: "Summer Camps", price: "Contact", desc: "Seasonal camps + Marbella abroad" },
      { name: "Mentality Coaching", price: "Contact", desc: "With Marian Jelínek" }
    ],
    coaches: [
      { name: "Ondřej Dohnal", credential: "30+ years", background: "Coached Karolína Plíšková (WTA #1) and Kateřina Siniaková", atpWta: false, bestRanking: null, rankingNote: "Coached WTA #1" }
    ],
    bestCoachRanking: null,
    coachedTopPlayer: 1,
    facilities: "5 clay + 2 indoor courts, gym, restaurant. Expansion planned.",
    notableAlumni: ["Karolína Plíšková (WTA #1)"],
    description: "Founded 2020. Karolína Plíšková (WTA #1) personally trains here. Mental coach Marian Jelínek on staff."
  },
  {
    id: "cltk-praha",
    name: "I. ČLTK Praha",
    country: "Czech Republic",
    countryFlag: "🇨🇿",
    city: "Prague",
    website: "https://cltk.cz/en/tennis-lessons/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Václav Havel Airport Prague", code: "PRG", distance: "17 km", driveTime: "25 min" },
    beach: { distance: null, description: "Landlocked — Baltic ~430 km; Adriatic ~700 km" },
    climate: "prague",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "One of Prague's oldest and most traditional tennis clubs",
    notableAlumni: [],
    description: "Historic Czech club. Coaches include Ondřej Macek (30 yrs, speaks CZ/EN/DE/RU) and Jan Kurz (50 yrs exp)."
  },
  {
    id: "love4tennis",
    name: "Love4Tennis — Dominika Cibulková Academy",
    country: "Slovakia",
    countryFlag: "🇸🇰",
    city: "Bratislava",
    website: "https://love4tennis.com/",
    individualLessons: true,
    boarding: true,
    level: "Elite",
    starred: true,
    airport: { name: "M. R. Štefánik Airport Bratislava", code: "BTS", distance: "9 km", driveTime: "15 min" },
    beach: { distance: null, description: "Landlocked — Adriatic ~530 km / ~6 hrs drive. Also Vienna VIE ~60 km." },
    climate: "bratislava",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Professional Annual", price: "Contact", desc: "Full-service: sparring, fitness, regeneration, tutoring, accommodation" },
      { name: "Kids Tennis", price: "Contact", desc: "Ages 5–12" },
      { name: "US Scholarship Program", price: "Contact", desc: "Tennis + US university studies" },
      { name: "Tennis Camp", price: "Contact", desc: "Advanced players 10+, summer" },
      { name: "Online Training", price: "Contact", desc: "Fitness, tennis, mental coaching" }
    ],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Full-service academy. 60+ pro players from 15 countries. 5 in ATP/WTA TOP 100.",
    notableAlumni: ["Elena Rybakina (WTA #3, Wimbledon champion)", "Filip Polášek (ATP #1 doubles)", "Lukáš Lacko (ATP #64)", "Kristína Kučová (WTA #67)"],
    description: "Named after Dominika Cibulková (WTA #4). One of Europe's best academies. Rybakina as alumna."
  },
  {
    id: "hta-academy",
    name: "HTA Academy",
    country: "Slovakia",
    countryFlag: "🇸🇰",
    city: "Bratislava",
    website: "https://htaacademy.sk/en/home-2/",
    individualLessons: true,
    boarding: false,
    level: "Recreational",
    starred: false,
    airport: { name: "M. R. Štefánik Airport Bratislava", code: "BTS", distance: "9 km", driveTime: "15 min" },
    beach: { distance: null, description: "Landlocked — Adriatic ~530 km" },
    climate: "bratislava",
    priceRange: { from: 37, to: 45, unit: "hour", display: "€37–€45/hr" },
    programs: [
      { name: "Children (from age 3)", price: "Varies", desc: "Early development" },
      { name: "Adult Training", price: "€37-45/hr", desc: "Individual and group" }
    ],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Community-focused, equipment rental included",
    notableAlumni: [],
    description: "Affordable individual lessons from €37/hr. Children from age 3, adults, group training."
  },
  {
    id: "tenis-kozerki",
    name: "Tenis Kozerki Tennis Academy",
    country: "Poland",
    countryFlag: "🇵🇱",
    city: "Kozerki (near Warsaw)",
    website: "https://www.teniskozerki.pl/?lang=en",
    individualLessons: true,
    boarding: true,
    level: "All levels",
    starred: true,
    airport: { name: "Warsaw Chopin Airport", code: "WAW", distance: "38 km", driveTime: "30 min" },
    beach: { distance: null, description: "Baltic Sea (Gdańsk) ~370 km / ~4.5 hrs drive" },
    climate: "warsaw",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "Full School Year Stay", price: "Contact", desc: "Ages 14-18, 10-month residential" },
      { name: "Monthly/Weekly Stays", price: "Contact", desc: "Ages 12-20" },
      { name: "Professional Players", price: "Contact", desc: "European tour base between ATP/WTA tournaments" },
      { name: "Summer Camps", price: "Contact", desc: "U12/U14, U16/U18" }
    ],
    coaches: [],
    bestCoachRanking: 40,
    facilities: "21 courts, sports hall, gym, cryocabin, saunas, pools, padel, squash, hotel, 3,000-seat stands",
    notableAlumni: [],
    description: "Most modern tennis complex in Poland. Coach connection to Linda Ferrando (WTA #40). Hosts ITF/WTA/ATP tournaments."
  },
  {
    id: "vicio-fede",
    name: "Vicio & Fede Tennis (Breakpoint Warsaw)",
    country: "Poland",
    countryFlag: "🇵🇱",
    city: "Warsaw",
    website: "https://tenniswarszawa.pl/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Warsaw Chopin Airport", code: "WAW", distance: "10 km", driveTime: "20 min" },
    beach: { distance: null, description: "Baltic Sea (Gdańsk) ~340 km / ~4 hrs drive" },
    climate: "warsaw",
    priceRange: { from: 32, to: 41, unit: "hour", display: "~€32–€41/hr" },
    programs: [
      { name: "Private Lessons", price: "140 PLN (~€32)", desc: "1-on-1" },
      { name: "Group (3-4)", price: "180 PLN (~€41) total", desc: "Shared cost" }
    ],
    coaches: [
      { name: "Federico", credential: "Coach", background: "Trained alongside Linda Ferrando (WTA #40)", atpWta: false, bestRanking: null }
    ],
    bestCoachRanking: null,
    facilities: "Multiple court locations across Warsaw. Languages: EN, IT, DE, PL",
    notableAlumni: [],
    description: "International coaching in English. Ideal for expats. Affordable private lessons from ~€32/hr."
  },
  {
    id: "mera-legia",
    name: "WKT Mera Warsaw & Legia Warsaw Tennis",
    country: "Poland",
    countryFlag: "🇵🇱",
    city: "Warsaw",
    website: null,
    individualLessons: true,
    boarding: false,
    level: "Junior/Dev",
    starred: false,
    airport: { name: "Warsaw Chopin Airport", code: "WAW", distance: "10 km", driveTime: "20 min" },
    beach: { distance: null, description: "Baltic Sea (Gdańsk) ~340 km / ~4 hrs drive" },
    climate: "warsaw",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Premier Polish multi-sport clubs",
    notableAlumni: ["Iga Świątek (WTA #1, 5× Grand Slam champion)"],
    description: "Where Iga Świątek trained as a junior (Mera) and continued at age 14 (Legia)."
  },
  {
    id: "hanescu-academy",
    name: "Victor Hănescu Academy (AVH)",
    country: "Romania",
    countryFlag: "🇷🇴",
    city: "Bucharest",
    website: "https://www.academiavictorhanescu.ro/?lng=en",
    individualLessons: true,
    boarding: false,
    level: "Junior/Pro",
    starred: true,
    airport: { name: "Henri Coandă International Airport", code: "OTP", distance: "18 km", driveTime: "25 min" },
    beach: { distance: null, description: "Black Sea coast (Constanța) — ~225 km / 2.5h drive" },
    climate: "bucharest",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [
      { name: "AVH Kids / Mini Tennis", price: "Contact", desc: "Monthly tournaments" },
      { name: "Junior Development", price: "Contact", desc: "Long-term athlete development" },
      { name: "Performance", price: "Contact", desc: "Mental, emotional, physical preparation" }
    ],
    coaches: [
      { name: "Victor Hănescu", credential: "Former ATP Player", background: "ATP #26 (2007), Romanian No. 1", atpWta: true, bestRanking: 26, rankingNote: "ATP #26" }
    ],
    bestCoachRanking: 26,
    facilities: "Professional courts in Bucharest",
    notableAlumni: [],
    description: "Founded by Victor Hănescu (ATP #26). Long-term sports development philosophy."
  },
  {
    id: "bucharest-tennis",
    name: "Bucharest Tennis",
    country: "Romania",
    countryFlag: "🇷🇴",
    city: "Bucharest",
    website: "https://bucharest.tennis/en/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Henri Coandă International Airport", code: "OTP", distance: "18 km", driveTime: "25 min" },
    beach: { distance: null, description: "Black Sea coast (Constanța) — ~225 km / 2.5h drive" },
    climate: "bucharest",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "PTR Professional certified coaching",
    notableAlumni: [],
    description: "PTR Professional certified coach. All ages, recreational and competitive."
  },
  {
    id: "sofia-360",
    name: "Sofia Tennis Club 360",
    country: "Bulgaria",
    countryFlag: "🇧🇬",
    city: "Sofia",
    website: "https://360tennis.bg/en/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Sofia Airport", code: "SOF", distance: "10 km", driveTime: "15 min" },
    beach: { distance: null, description: "Black Sea (Burgas) — ~380 km / 4h drive" },
    climate: "sofia",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Historic parkland (Borisova Garden), near Vasil Levski Stadium",
    notableAlumni: [],
    description: "Heir to Bulgaria's oldest tennis club (est. 1896). Grigor Dimitrov trained locally before moving to France."
  },
  {
    id: "romai-tennis",
    name: "Római Tennis Academy",
    country: "Hungary",
    countryFlag: "🇭🇺",
    city: "Budapest",
    website: null,
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Budapest Ferenc Liszt International Airport", code: "BUD", distance: "16 km", driveTime: "25 min" },
    beach: { distance: null, description: "Landlocked — Adriatic ~480 km. Lake Balaton ~130 km / 1.5h drive" },
    climate: "budapest",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "10 clay + 1 soft court (year-round), squash, 25m pool, wellness. 2-hectare along Danube.",
    notableAlumni: [],
    description: "Most prestigious tennis academy in Hungary. Beautiful Danube riverbank location."
  },
  {
    id: "szepvolgyi",
    name: "Szépvölgyi Tennis Academy",
    country: "Hungary",
    countryFlag: "🇭🇺",
    city: "Budapest",
    website: "https://szepvolgyi.hu/en/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Budapest Ferenc Liszt International Airport", code: "BUD", distance: "16 km", driveTime: "25 min" },
    beach: { distance: null, description: "Landlocked — Adriatic ~480 km. Lake Balaton ~130 km / 1.5h drive" },
    climate: "budapest",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "3 clay + 3 hard courts. Bilingual coaching (Hungarian/English).",
    notableAlumni: [],
    description: "Bilingual (Hungarian/English) coaching. Beginner to professional competition preparation."
  },
  {
    id: "breskvar",
    name: "Tennis Academy Breskvar",
    country: "Slovenia",
    countryFlag: "🇸🇮",
    city: "Ljubljana",
    website: "https://tenis-klub-breskvar.si/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Ljubljana Jože Pučnik Airport", code: "LJU", distance: "26 km", driveTime: "25 min" },
    beach: { distance: 95, description: "Adriatic coast (Koper/Piran) — ~95 km / 1h drive" },
    climate: "ljubljana",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Premier tennis facility in Ljubljana",
    notableAlumni: [],
    description: "Premier tennis facility in Ljubljana. Beginner to advanced, competitive matches."
  },
  {
    id: "medvedev-academy",
    name: "Medvedev Tennis Academy",
    country: "Ukraine",
    countryFlag: "🇺🇦",
    city: "Kyiv (Pogreby)",
    website: "https://kiev.tennis/en/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: true,
    airport: { name: "Boryspil International Airport", code: "KBP", distance: "33 km", driveTime: "40 min" },
    beach: { distance: null, description: "Inland — Black Sea coast (Odesa) ~480 km / 5.5h drive" },
    climate: "kyiv",
    priceRange: { from: null, to: null, unit: "month", display: "Varies (50% off first lesson)" },
    programs: [
      { name: "Baby Tennis", price: "Varies", desc: "Ages 3–8" },
      { name: "Children's Tennis", price: "Varies", desc: "Ages 9–18" },
      { name: "Top Tennis", price: "Varies", desc: "Young professionals" },
      { name: "Adult Training", price: "Varies", desc: "Amateurs and professionals" }
    ],
    coaches: [
      { name: "Andrey Medvedev", credential: "Former ATP Player", background: "ATP #4 (1994), French Open finalist 1999, President of Ukrainian Tennis Federation", atpWta: true, bestRanking: 4, rankingNote: "ATP #4" }
    ],
    bestCoachRanking: 4,
    facilities: "Indoor/outdoor courts (clay), hosted Davis Cup 2021, fitness, massage, rehab",
    notableAlumni: [],
    description: "Headed by Andrey Medvedev (ATP #4, French Open finalist). Personal sessions available with Medvedev himself."
  },
  {
    id: "mta-kyiv",
    name: "International Tennis Academy (MTA)",
    country: "Ukraine",
    countryFlag: "🇺🇦",
    city: "Kyiv",
    website: "https://tennisacademy.com.ua/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Boryspil International Airport", code: "KBP", distance: "33 km", driveTime: "40 min" },
    beach: { distance: null, description: "Inland — Black Sea coast ~480 km" },
    climate: "kyiv",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "37 tennis courts, 6 types of surfaces — world-class",
    notableAlumni: [],
    description: "37 courts with 6 surface types. Comprehensive tennis school."
  },
  {
    id: "vilnius-academy",
    name: "Vilnius Tennis Academy",
    country: "Lithuania",
    countryFlag: "🇱🇹",
    city: "Vilnius",
    website: "https://www.tenisoakademija.lt/en",
    individualLessons: true,
    boarding: false,
    level: "Junior/Dev",
    starred: false,
    airport: { name: "Vilnius International Airport", code: "VNO", distance: "7 km", driveTime: "15 min" },
    beach: { distance: null, description: "Baltic Sea (Palanga/Klaipėda) — ~310 km / 3.5h drive" },
    climate: "vilnius",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Largest tennis academy in Lithuania — 500+ youth",
    notableAlumni: [],
    description: "Largest in Lithuania (500+ youth). Financially supports most promising athletes."
  },
  {
    id: "riga-academy",
    name: "Riga Tennis Academy",
    country: "Latvia",
    countryFlag: "🇱🇻",
    city: "Riga",
    website: "http://www.rigatennisacademy.lv/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Riga International Airport", code: "RIX", distance: "10 km", driveTime: "15 min" },
    beach: { distance: 25, description: "🏖️ Jūrmala beach resort — ~25 km / 30 min drive" },
    climate: "riga",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Founded by two internationally experienced tennis players/coaches",
    notableAlumni: [],
    description: "Founded by ex-international players. Children from age 5 through adults, tailored training plans."
  },
  {
    id: "tenisa-akademija",
    name: "Tenisa Akadēmija",
    country: "Latvia",
    countryFlag: "🇱🇻",
    city: "Riga",
    website: "http://tenisaakademija.lv/",
    individualLessons: true,
    boarding: false,
    level: "All levels",
    starred: false,
    airport: { name: "Riga International Airport", code: "RIX", distance: "10 km", driveTime: "15 min" },
    beach: { distance: 25, description: "🏖️ Jūrmala beach resort — ~25 km / 30 min drive" },
    climate: "riga",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Comprehensive: sparring, fitness, distance learning, language courses, competitions abroad",
    notableAlumni: [],
    description: "Comprehensive program including language courses, distance learning, and coach-assisted competitions abroad."
  },
  {
    id: "us-tenniseakadeemia",
    name: "US Tenniseakadeemia",
    country: "Estonia",
    countryFlag: "🇪🇪",
    city: "Tallinn",
    website: null,
    individualLessons: null,
    boarding: false,
    level: "Unknown",
    starred: false,
    airport: { name: "Lennart Meri Tallinn Airport", code: "TLL", distance: "4 km", driveTime: "10 min" },
    beach: { distance: 8, description: "🏖️ Pirita Beach — ~8 km / 15 min. Tallinn is coastal (Gulf of Finland)" },
    climate: "tallinn",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Sõjakooli 10, Tallinn",
    notableAlumni: [],
    description: "Tallinn-based tennis academy."
  },
  {
    id: "robbyo",
    name: "Robbyo Tennis Academy",
    country: "Estonia",
    countryFlag: "🇪🇪",
    city: "Tallinn",
    website: null,
    individualLessons: null,
    boarding: false,
    level: "Unknown",
    starred: false,
    airport: { name: "Lennart Meri Tallinn Airport", code: "TLL", distance: "4 km", driveTime: "10 min" },
    beach: { distance: 8, description: "🏖️ Pirita Beach — ~8 km / 15 min. Tallinn is coastal (Gulf of Finland)" },
    climate: "tallinn",
    priceRange: { from: null, to: null, unit: "month", display: "Contact for pricing" },
    programs: [],
    coaches: [],
    bestCoachRanking: null,
    facilities: "Peterburi Tee 46, Tallinn",
    notableAlumni: [],
    description: "Tallinn-based tennis academy."
  }
];

const CLIMATE_DATA = {
  belgrade: {
    city: "Belgrade", country: "Serbia",
    months: [
      { month: "Jan", temp: 2, rain: 54, rainyDays: 13, wind: 11 },
      { month: "Feb", temp: 5, rain: 42, rainyDays: 12, wind: 12 },
      { month: "Mar", temp: 9, rain: 54, rainyDays: 13, wind: 12 },
      { month: "Apr", temp: 13, rain: 50, rainyDays: 12, wind: 11 },
      { month: "May", temp: 17, rain: 94, rainyDays: 14, wind: 11 },
      { month: "Jun", temp: 22, rain: 87, rainyDays: 13, wind: 9 },
      { month: "Jul", temp: 24, rain: 68, rainyDays: 10, wind: 9 },
      { month: "Aug", temp: 24, rain: 56, rainyDays: 8, wind: 9 },
      { month: "Sep", temp: 19, rain: 40, rainyDays: 8, wind: 10 },
      { month: "Oct", temp: 15, rain: 48, rainyDays: 8, wind: 11 },
      { month: "Nov", temp: 8, rain: 58, rainyDays: 8, wind: 11 },
      { month: "Dec", temp: 4, rain: 54, rainyDays: 9, wind: 11 }
    ]
  },
  "mali-losinj": {
    city: "Mali Lošinj", country: "Croatia",
    months: [
      { month: "Jan", temp: 6, rain: 88, rainyDays: 13, wind: 13 },
      { month: "Feb", temp: 6, rain: 78, rainyDays: 12, wind: 12 },
      { month: "Mar", temp: 9, rain: 80, rainyDays: 13, wind: 11 },
      { month: "Apr", temp: 12, rain: 82, rainyDays: 14, wind: 9 },
      { month: "May", temp: 17, rain: 75, rainyDays: 13, wind: 9 },
      { month: "Jun", temp: 20, rain: 66, rainyDays: 13, wind: 8 },
      { month: "Jul", temp: 23, rain: 51, rainyDays: 10, wind: 8 },
      { month: "Aug", temp: 23, rain: 86, rainyDays: 10, wind: 8 },
      { month: "Sep", temp: 20, rain: 106, rainyDays: 11, wind: 9 },
      { month: "Oct", temp: 15, rain: 114, rainyDays: 12, wind: 10 },
      { month: "Nov", temp: 11, rain: 141, rainyDays: 14, wind: 12 },
      { month: "Dec", temp: 7, rain: 103, rainyDays: 13, wind: 12 }
    ]
  },
  biograd: {
    city: "Biograd na Moru", country: "Croatia",
    months: [
      { month: "Jan", temp: 6, rain: 92, rainyDays: 11, wind: 13 },
      { month: "Feb", temp: 6, rain: 90, rainyDays: 10, wind: 13 },
      { month: "Mar", temp: 10, rain: 88, rainyDays: 10, wind: 12 },
      { month: "Apr", temp: 14, rain: 96, rainyDays: 10, wind: 11 },
      { month: "May", temp: 18, rain: 83, rainyDays: 9, wind: 10 },
      { month: "Jun", temp: 22, rain: 54, rainyDays: 7, wind: 9 },
      { month: "Jul", temp: 25, rain: 36, rainyDays: 5, wind: 9 },
      { month: "Aug", temp: 25, rain: 55, rainyDays: 5, wind: 9 },
      { month: "Sep", temp: 20, rain: 107, rainyDays: 8, wind: 10 },
      { month: "Oct", temp: 16, rain: 119, rainyDays: 10, wind: 11 },
      { month: "Nov", temp: 11, rain: 154, rainyDays: 12, wind: 13 },
      { month: "Dec", temp: 7, rain: 117, rainyDays: 11, wind: 13 }
    ]
  },
  split: {
    city: "Split", country: "Croatia",
    months: [
      { month: "Jan", temp: 8, rain: 95, rainyDays: 13, wind: 11 },
      { month: "Feb", temp: 9, rain: 86, rainyDays: 13, wind: 11 },
      { month: "Mar", temp: 11, rain: 89, rainyDays: 13, wind: 10 },
      { month: "Apr", temp: 13, rain: 83, rainyDays: 13, wind: 9 },
      { month: "May", temp: 17, rain: 69, rainyDays: 12, wind: 8 },
      { month: "Jun", temp: 21, rain: 74, rainyDays: 13, wind: 7 },
      { month: "Jul", temp: 24, rain: 46, rainyDays: 10, wind: 7 },
      { month: "Aug", temp: 24, rain: 64, rainyDays: 9, wind: 7 },
      { month: "Sep", temp: 21, rain: 75, rainyDays: 10, wind: 8 },
      { month: "Oct", temp: 16, rain: 102, rainyDays: 12, wind: 9 },
      { month: "Nov", temp: 12, rain: 134, rainyDays: 14, wind: 10 },
      { month: "Dec", temp: 8, rain: 127, rainyDays: 14, wind: 11 }
    ]
  },
  prostejov: {
    city: "Prostějov", country: "Czech Republic",
    months: [
      { month: "Jan", temp: -2.8, rain: 30, rainyDays: 12, wind: 15 },
      { month: "Feb", temp: -0.8, rain: 31, rainyDays: 11, wind: 15 },
      { month: "Mar", temp: 3.2, rain: 31, rainyDays: 11, wind: 15 },
      { month: "Apr", temp: 8.4, rain: 40, rainyDays: 11, wind: 14 },
      { month: "May", temp: 13.5, rain: 67, rainyDays: 14, wind: 13 },
      { month: "Jun", temp: 16.4, rain: 85, rainyDays: 15, wind: 12 },
      { month: "Jul", temp: 17.9, rain: 71, rainyDays: 14, wind: 11 },
      { month: "Aug", temp: 17.4, rain: 67, rainyDays: 13, wind: 11 },
      { month: "Sep", temp: 13.8, rain: 43, rainyDays: 11, wind: 12 },
      { month: "Oct", temp: 8.7, rain: 38, rainyDays: 10, wind: 13 },
      { month: "Nov", temp: 3.3, rain: 45, rainyDays: 13, wind: 14 },
      { month: "Dec", temp: -0.9, rain: 35, rainyDays: 13, wind: 14 }
    ]
  },
  prague: {
    city: "Prague", country: "Czech Republic",
    months: [
      { month: "Jan", temp: -0.3, rain: 43, rainyDays: 10, wind: 14 },
      { month: "Feb", temp: 0.7, rain: 37, rainyDays: 8, wind: 14 },
      { month: "Mar", temp: 4.4, rain: 49, rainyDays: 8, wind: 18 },
      { month: "Apr", temp: 9.6, rain: 45, rainyDays: 8, wind: 14 },
      { month: "May", temp: 14.2, rain: 71, rainyDays: 11, wind: 14 },
      { month: "Jun", temp: 17.8, rain: 82, rainyDays: 11, wind: 14 },
      { month: "Jul", temp: 19.8, rain: 85, rainyDays: 12, wind: 14 },
      { month: "Aug", temp: 19.6, rain: 75, rainyDays: 10, wind: 14 },
      { month: "Sep", temp: 15.0, rain: 60, rainyDays: 8, wind: 14 },
      { month: "Oct", temp: 9.9, rain: 46, rainyDays: 8, wind: 14 },
      { month: "Nov", temp: 5.0, rain: 47, rainyDays: 8, wind: 14 },
      { month: "Dec", temp: 1.2, rain: 47, rainyDays: 9, wind: 14 }
    ]
  },
  bratislava: {
    city: "Bratislava", country: "Slovakia",
    months: [
      { month: "Jan", temp: -0.4, rain: 39, rainyDays: 6, wind: 15 },
      { month: "Feb", temp: 1.4, rain: 37, rainyDays: 6, wind: 16 },
      { month: "Mar", temp: 5.5, rain: 46, rainyDays: 7, wind: 15 },
      { month: "Apr", temp: 10.9, rain: 51, rainyDays: 7, wind: 15 },
      { month: "May", temp: 15.4, rain: 72, rainyDays: 8, wind: 14 },
      { month: "Jun", temp: 19.3, rain: 75, rainyDays: 8, wind: 13 },
      { month: "Jul", temp: 21.3, rain: 81, rainyDays: 8, wind: 13 },
      { month: "Aug", temp: 20.9, rain: 68, rainyDays: 7, wind: 12 },
      { month: "Sep", temp: 16.2, rain: 70, rainyDays: 7, wind: 12 },
      { month: "Oct", temp: 11.1, rain: 49, rainyDays: 7, wind: 12 },
      { month: "Nov", temp: 6.2, rain: 51, rainyDays: 7, wind: 14 },
      { month: "Dec", temp: 1.0, rain: 44, rainyDays: 7, wind: 15 }
    ]
  },
  warsaw: {
    city: "Warsaw", country: "Poland",
    months: [
      { month: "Jan", temp: -1.5, rain: 37, rainyDays: 12, wind: 15 },
      { month: "Feb", temp: 0.0, rain: 33, rainyDays: 10, wind: 16 },
      { month: "Mar", temp: 3.5, rain: 38, rainyDays: 10, wind: 15 },
      { month: "Apr", temp: 8.5, rain: 43, rainyDays: 10, wind: 13 },
      { month: "May", temp: 14.0, rain: 62, rainyDays: 11, wind: 12 },
      { month: "Jun", temp: 18.0, rain: 70, rainyDays: 11, wind: 11 },
      { month: "Jul", temp: 19.5, rain: 80, rainyDays: 12, wind: 11 },
      { month: "Aug", temp: 19.0, rain: 64, rainyDays: 10, wind: 11 },
      { month: "Sep", temp: 14.5, rain: 54, rainyDays: 10, wind: 12 },
      { month: "Oct", temp: 9.5, rain: 42, rainyDays: 10, wind: 13 },
      { month: "Nov", temp: 3.5, rain: 42, rainyDays: 12, wind: 15 },
      { month: "Dec", temp: -0.5, rain: 43, rainyDays: 13, wind: 15 }
    ]
  },
  bucharest: {
    city: "Bucharest", country: "Romania",
    months: [
      { month: "Jan", temp: -1, rain: 40, rainyDays: 8, wind: 14 },
      { month: "Feb", temp: 1, rain: 36, rainyDays: 7, wind: 15 },
      { month: "Mar", temp: 6, rain: 38, rainyDays: 8, wind: 14 },
      { month: "Apr", temp: 12, rain: 46, rainyDays: 9, wind: 13 },
      { month: "May", temp: 17, rain: 70, rainyDays: 11, wind: 11 },
      { month: "Jun", temp: 21, rain: 77, rainyDays: 10, wind: 10 },
      { month: "Jul", temp: 23, rain: 64, rainyDays: 8, wind: 10 },
      { month: "Aug", temp: 23, rain: 58, rainyDays: 7, wind: 9 },
      { month: "Sep", temp: 18, rain: 42, rainyDays: 6, wind: 10 },
      { month: "Oct", temp: 12, rain: 32, rainyDays: 6, wind: 11 },
      { month: "Nov", temp: 5, rain: 48, rainyDays: 8, wind: 13 },
      { month: "Dec", temp: 0, rain: 43, rainyDays: 9, wind: 14 }
    ]
  },
  sofia: {
    city: "Sofia", country: "Bulgaria",
    months: [
      { month: "Jan", temp: -1, rain: 33, rainyDays: 10, wind: 10 },
      { month: "Feb", temp: 1, rain: 31, rainyDays: 9, wind: 11 },
      { month: "Mar", temp: 5, rain: 38, rainyDays: 10, wind: 12 },
      { month: "Apr", temp: 10, rain: 51, rainyDays: 12, wind: 11 },
      { month: "May", temp: 15, rain: 73, rainyDays: 14, wind: 10 },
      { month: "Jun", temp: 19, rain: 75, rainyDays: 13, wind: 9 },
      { month: "Jul", temp: 21, rain: 53, rainyDays: 10, wind: 9 },
      { month: "Aug", temp: 21, rain: 46, rainyDays: 8, wind: 9 },
      { month: "Sep", temp: 16, rain: 38, rainyDays: 7, wind: 9 },
      { month: "Oct", temp: 11, rain: 35, rainyDays: 8, wind: 9 },
      { month: "Nov", temp: 5, rain: 43, rainyDays: 10, wind: 10 },
      { month: "Dec", temp: 0, rain: 40, rainyDays: 11, wind: 10 }
    ]
  },
  budapest: {
    city: "Budapest", country: "Hungary",
    months: [
      { month: "Jan", temp: 0, rain: 37, rainyDays: 8, wind: 13 },
      { month: "Feb", temp: 2, rain: 32, rainyDays: 7, wind: 14 },
      { month: "Mar", temp: 7, rain: 33, rainyDays: 7, wind: 14 },
      { month: "Apr", temp: 12, rain: 42, rainyDays: 8, wind: 13 },
      { month: "May", temp: 17, rain: 62, rainyDays: 10, wind: 12 },
      { month: "Jun", temp: 20, rain: 63, rainyDays: 9, wind: 11 },
      { month: "Jul", temp: 22, rain: 50, rainyDays: 8, wind: 10 },
      { month: "Aug", temp: 22, rain: 52, rainyDays: 7, wind: 10 },
      { month: "Sep", temp: 17, rain: 40, rainyDays: 6, wind: 10 },
      { month: "Oct", temp: 11, rain: 38, rainyDays: 7, wind: 11 },
      { month: "Nov", temp: 5, rain: 50, rainyDays: 9, wind: 13 },
      { month: "Dec", temp: 1, rain: 44, rainyDays: 9, wind: 13 }
    ]
  },
  ljubljana: {
    city: "Ljubljana", country: "Slovenia",
    months: [
      { month: "Jan", temp: 0, rain: 69, rainyDays: 11, wind: 7 },
      { month: "Feb", temp: 2, rain: 66, rainyDays: 10, wind: 8 },
      { month: "Mar", temp: 6, rain: 82, rainyDays: 11, wind: 9 },
      { month: "Apr", temp: 11, rain: 97, rainyDays: 13, wind: 9 },
      { month: "May", temp: 15, rain: 99, rainyDays: 14, wind: 8 },
      { month: "Jun", temp: 19, rain: 131, rainyDays: 14, wind: 7 },
      { month: "Jul", temp: 21, rain: 104, rainyDays: 12, wind: 7 },
      { month: "Aug", temp: 21, rain: 120, rainyDays: 11, wind: 7 },
      { month: "Sep", temp: 16, rain: 156, rainyDays: 11, wind: 6 },
      { month: "Oct", temp: 11, rain: 147, rainyDays: 12, wind: 6 },
      { month: "Nov", temp: 5, rain: 129, rainyDays: 13, wind: 7 },
      { month: "Dec", temp: 1, rain: 91, rainyDays: 12, wind: 7 }
    ]
  },
  kyiv: {
    city: "Kyiv", country: "Ukraine",
    months: [
      { month: "Jan", temp: -3, rain: 38, rainyDays: 14, wind: 14 },
      { month: "Feb", temp: -2, rain: 35, rainyDays: 12, wind: 15 },
      { month: "Mar", temp: 2, rain: 37, rainyDays: 11, wind: 14 },
      { month: "Apr", temp: 9, rain: 46, rainyDays: 11, wind: 13 },
      { month: "May", temp: 15, rain: 55, rainyDays: 13, wind: 12 },
      { month: "Jun", temp: 19, rain: 73, rainyDays: 13, wind: 11 },
      { month: "Jul", temp: 21, rain: 78, rainyDays: 13, wind: 10 },
      { month: "Aug", temp: 20, rain: 59, rainyDays: 10, wind: 10 },
      { month: "Sep", temp: 14, rain: 47, rainyDays: 9, wind: 11 },
      { month: "Oct", temp: 8, rain: 38, rainyDays: 9, wind: 12 },
      { month: "Nov", temp: 2, rain: 47, rainyDays: 13, wind: 14 },
      { month: "Dec", temp: -2, rain: 42, rainyDays: 15, wind: 14 }
    ]
  },
  vilnius: {
    city: "Vilnius", country: "Lithuania",
    months: [
      { month: "Jan", temp: -4, rain: 40, rainyDays: 18, wind: 16 },
      { month: "Feb", temp: -3, rain: 33, rainyDays: 14, wind: 16 },
      { month: "Mar", temp: 1, rain: 37, rainyDays: 13, wind: 15 },
      { month: "Apr", temp: 7, rain: 42, rainyDays: 12, wind: 14 },
      { month: "May", temp: 13, rain: 57, rainyDays: 13, wind: 12 },
      { month: "Jun", temp: 16, rain: 76, rainyDays: 13, wind: 11 },
      { month: "Jul", temp: 19, rain: 104, rainyDays: 14, wind: 11 },
      { month: "Aug", temp: 18, rain: 77, rainyDays: 12, wind: 11 },
      { month: "Sep", temp: 13, rain: 60, rainyDays: 12, wind: 12 },
      { month: "Oct", temp: 7, rain: 49, rainyDays: 12, wind: 14 },
      { month: "Nov", temp: 2, rain: 48, rainyDays: 16, wind: 16 },
      { month: "Dec", temp: -2, rain: 46, rainyDays: 18, wind: 16 }
    ]
  },
  riga: {
    city: "Riga", country: "Latvia",
    months: [
      { month: "Jan", temp: -3, rain: 42, rainyDays: 18, wind: 18 },
      { month: "Feb", temp: -3, rain: 31, rainyDays: 14, wind: 17 },
      { month: "Mar", temp: 0, rain: 33, rainyDays: 13, wind: 16 },
      { month: "Apr", temp: 6, rain: 38, rainyDays: 11, wind: 15 },
      { month: "May", temp: 12, rain: 44, rainyDays: 11, wind: 13 },
      { month: "Jun", temp: 16, rain: 62, rainyDays: 12, wind: 12 },
      { month: "Jul", temp: 19, rain: 76, rainyDays: 13, wind: 12 },
      { month: "Aug", temp: 18, rain: 77, rainyDays: 12, wind: 12 },
      { month: "Sep", temp: 13, rain: 70, rainyDays: 13, wind: 14 },
      { month: "Oct", temp: 7, rain: 87, rainyDays: 16, wind: 16 },
      { month: "Nov", temp: 3, rain: 63, rainyDays: 17, wind: 18 },
      { month: "Dec", temp: -1, rain: 49, rainyDays: 18, wind: 18 }
    ]
  },
  tallinn: {
    city: "Tallinn", country: "Estonia",
    months: [
      { month: "Jan", temp: -3, rain: 49, rainyDays: 19, wind: 20 },
      { month: "Feb", temp: -4, rain: 33, rainyDays: 15, wind: 19 },
      { month: "Mar", temp: -1, rain: 33, rainyDays: 13, wind: 18 },
      { month: "Apr", temp: 4, rain: 33, rainyDays: 11, wind: 16 },
      { month: "May", temp: 10, rain: 37, rainyDays: 10, wind: 14 },
      { month: "Jun", temp: 15, rain: 57, rainyDays: 12, wind: 13 },
      { month: "Jul", temp: 17, rain: 72, rainyDays: 13, wind: 12 },
      { month: "Aug", temp: 17, rain: 78, rainyDays: 13, wind: 13 },
      { month: "Sep", temp: 12, rain: 67, rainyDays: 14, wind: 15 },
      { month: "Oct", temp: 6, rain: 76, rainyDays: 16, wind: 18 },
      { month: "Nov", temp: 2, rain: 61, rainyDays: 17, wind: 20 },
      { month: "Dec", temp: -1, rain: 54, rainyDays: 19, wind: 22 }
    ]
  }
};

const COUNTRIES = [...new Set(ACADEMIES.map(a => a.country))];
